### PR TITLE
add support for DoubleSizeIdentifier

### PR DESCRIPTION
**Pull request by jtjeferreira**

### CODE REVIEW

**Comment by tilmanginzel** [comment]
Hey @ivantopo, any chance that the support for 128 bit trace ids can get merged and published in the next release? We are currently facing the issue that our api consumers are sending 128 bit long trace ids which cannot be correlated in Jaeger, as they are stripped down to 64 bits in Kamon.

That would be highly appreciated. :)

@jtjeferreira There are currently merge conflicts (hopefully small ones), so maybe the pull request can be updated. If not, I could try to provide a new one.

**Comment by jtjeferreira** [comment]
I fixed conflicts via github webui :) Lets check if Travis is happy...

**Comment by tilmanginzel** [comment]
Thanks for the fast update. :) Travis is not happy, but it's not related to your changes:
```
unresolved dependency: com.geirsson#sbt-scalafmt;1.5.1: not found
```
Might be related to this: https://github.com/scalameta/scalafmt/issues/1008

**Comment by jtjeferreira** [comment]
@tilmanginzel thanks for the pointer... updated sbt and it worked

**Comment by tilmanginzel** [comment]
Perfect!

**Comment by tilmanginzel** [comment]
Hey @ivantopo, @dpsoft, sorry for bumping this issue again but maybe it was just overlooked last time. Any chance this can get merged so we don't have to use a custom fork? :)

**Comment by ivantopo** [comment]
Hey @jtjeferreira, thanks a lot for the PR! @tilmanginzel, indeed it went overlooked, sorry about that.. I'll release it right away!

**Comment by tilmanginzel** [comment]
Hey @ivantopo, no worries and thanks a lot for merging! We were just about to create our custom JaegerReporter for this, but now that's not necessary anymore. :)

**Comment by ivantopo** [comment]
:tada: this was published as [v1.0.3](https://github.com/kamon-io/kamon-jaeger/releases/tag/v1.0.3), now on its way to Maven Central!

Thanks a lot for the patience :pray:

**Comment by tilmanginzel** [comment]
Cool! If I am not mistaken the v1.0.3 release also contains support for environment tags (#9), so maybe you want to add that in the release notes.

**Comment by ivantopo** [comment]
Thanks @tilmanginzel, you be on fire!

**Pull request merged**
